site_name: 我的星标库
site_description: GitHub Star 项目分类导航

theme:
  name: material
  language: zh
  features:
    # 🌟 核心修改：删除了 navigation.tabs，让分类菜单常驻在左侧不消失
    - navigation.top # 开启返回顶部按钮
    - search.suggest # 搜索建议
    - navigation.tracking # 当你在右侧滚动时，左侧菜单会自动高亮你所在的位置
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到暗夜模式
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: 切换到日间模式

markdown_extensions:
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list

plugins:
  - search
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true

extra_css:
  - stylesheets/extra.css

nav:
  - 🏠 首页: index.md
  - 🤖 最新 Star 盲盒: auto_stars.md
  - 🔖 bookmark: bookmarks.md
