site_name: 我的星标武器库 # 改这里：你的网站主标题
site_description: GitHub Star 项目分类导航
theme:
  name: material
  language: zh # 设置为中文，自带的搜索框会支持中文分词
  features:
    - navigation.tabs # 开启顶部导航栏
    - navigation.top # 开启返回顶部按钮
    - search.suggest # 搜索建议

# Markdown 扩展语法支持（表格、Emoji等）
markdown_extensions:
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list # 允许你给文字加标签样式
extra_css:
  - stylesheets/extra.css
nav:
  - 🏠 首页: index.md
  - 🤖 最新 Star 盲盒: auto_stars.md # <-- 加上这一行
